development:
  adapter:  mysql2
  database: nexdocron_development
  username: root
  password:

test:
  adapter:  mysql2
  database: nexdocron_test
  username: root
  password:

production:
  adapter:  mysql2
  database: nexdocron_production
  username: root
  password:
